version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    env_file: .env
    container_name: foodgram_backend
    build: ./backend 
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    container_name: foodgram_frontend
    command: cp -r /app/build/. /static/
    build: ./frontend
    volumes:
      # - ./frontend/:/app/result_build/
      - static:/static
  gateway:
    # image: tnkqq/kittygram_gateway
    build: ./nginx
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - static:/static
      - media:/app/media/