# Generated by Django 3.2.3 on 2024-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20240921_1624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                help_text="Максимум 64 символов.",
                max_length=64,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Не более 32 символов",
                max_length=128,
                verbose_name="Название",
            ),
        ),
    ]
