# Generated by Django 3.2.3 on 2024-09-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20240921_1625"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
