# Generated by Django 3.2.3 on 2024-09-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20240923_2011"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingridients",
            new_name="ingredients",
        ),
    ]
