# Generated by Django 3.2.3 on 2024-09-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_rename_ingridients_recipe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="avatar",
        ),
    ]
