# Generated by Django 3.2.3 on 2024-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="amount",
            new_name="amnt",
        ),
    ]
