# Generated by Django 3.2.3 on 2024-09-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_rename_amount_recipeingredient_amnt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="amnt",
            new_name="amount",
        ),
    ]
