# Generated by Django 3.2.3 on 2024-09-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_rename_amnt_recipeingredient_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
