# Generated by Django 3.2.3 on 2024-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                help_text="Максимум 64 символов.",
                max_length=64,
                verbose_name="Единица измерения",
            ),
        ),
    ]
