# Generated by Django 3.2.3 on 2024-09-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Follow",
            new_name="Subscription",
        ),
    ]
