# Generated by Django 3.2.3 on 2024-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="Не более 150 символов",
                max_length=150,
                verbose_name="Имя",
            ),
        ),
    ]
