# Generated by Django 3.2 on 2024-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_alter_favoriterecipe_recipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoriterecipe",
            options={
                "verbose_name": "Избранный Рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецепте",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default=None, upload_to="users/avatars/"),
        ),
    ]
