# Generated by Django 3.2 on 2024-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_auto_20241001_1330"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="uniqueRecipeIngredient"
            ),
        ),
    ]
