# Generated by Django 3.2 on 2024-10-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0022_recipeingredient_uniquerecipeingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="uniqueRecipeIngredient",
        ),
    ]
