# Generated by Django 3.2 on 2024-10-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0025_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="recipes.recipe",
            ),
        ),
    ]
